LABELS: dict[str, str] = {
    # RiskLevel
    "no_action_needed": "No Action Needed",
    "review_recommended": "Review Recommended",
    "action_required": "Action Required",
    "urgent_review": "Urgent Review",
    # DiffFlag
    "premium_increase_high": "High Premium Increase",
    "premium_increase_critical": "Critical Premium Increase",
    "premium_decrease": "Premium Decrease",
    "carrier_change": "Carrier Change",
    "liability_limit_decrease": "Liability Limit Decrease",
    "deductible_increase": "Deductible Increase",
    "coverage_dropped": "Coverage Dropped",
    "coverage_added": "Coverage Added",
    "vehicle_added": "Vehicle Added",
    "vehicle_removed": "Vehicle Removed",
    "driver_added": "Driver Added",
    "driver_removed": "Driver Removed",
    "endorsement_added": "Endorsement Added",
    "endorsement_removed": "Endorsement Removed",
    "notes_changed": "Notes Changed",
    "driver_violations": "Driver Violations",
    "sr22_filing": "SR-22 Filing",
    "youthful_operator": "Youthful Operator",
    "coverage_gap": "Coverage Gap",
    "claims_history": "Claims History",
    "property_risk": "Property Risk",
    "regulatory": "Regulatory Flag",
    "driver_risk_note": "Driver Risk (Notes)",
    # AnalysisType
    "risk_signal_extractor": "Risk Signal",
    "endorsement_comparison": "Endorsement Comparison",
    # FlagType (portfolio)
    "duplicate_medical": "Duplicate Medical",
    "duplicate_roadside": "Duplicate Roadside",
    "high_liability_exposure": "High Liability Exposure",
    "low_liability_exposure": "Low Liability Exposure",
    "premium_concentration": "Premium Concentration",
    "high_portfolio_increase": "High Portfolio Increase",
    # Severity
    "info": "Info",
    "warning": "Warning",
    "critical": "Critical",
    # FieldChange.field (policy change fields)
    "premium": "Premium",
    "carrier": "Carrier",
    "collision_deductible": "Collision Deductible",
    "comprehensive_deductible": "Comprehensive Deductible",
    "bodily_injury_limit": "Bodily Injury Limit",
    "property_damage_limit": "Property Damage Limit",
    "uninsured_motorist": "Uninsured Motorist",
    "medical_payments": "Medical Payments",
    "rental_reimbursement": "Rental Reimbursement",
    "roadside_assistance": "Roadside Assistance",
    "deductible": "Home Deductible",
    "coverage_a_dwelling": "Dwelling (Coverage A)",
    "coverage_b_other_structures": "Other Structures (Coverage B)",
    "coverage_c_personal_property": "Personal Property (Coverage C)",
    "coverage_d_loss_of_use": "Loss of Use (Coverage D)",
    "coverage_e_liability": "Liability (Coverage E)",
    "coverage_f_medical": "Medical Payments (Coverage F)",
    "water_backup": "Water Backup Coverage",
    "wind_hail_deductible": "Wind/Hail Deductible",
    "replacement_cost": "Replacement Cost",
}


def get_label(raw: str) -> str:
    return LABELS.get(raw, raw.replace("_", " ").title())
