from typing import Protocol

from app.domain.models.analytics import BatchRunRecord
from app.domain.models.review import BatchSummary, ReviewResult


class ReviewStore(Protocol):
    def get(self, policy_number: str) -> ReviewResult | None: ...
    def set(self, policy_number: str, result: ReviewResult) -> None: ...
    def clear(self) -> None: ...
    def values(self) -> list[ReviewResult]: ...


class HistoryStore(Protocol):
    def append(self, record: BatchRunRecord) -> None: ...
    def list(self) -> list[BatchRunRecord]: ...
    def __len__(self) -> int: ...


class JobStore(Protocol):
    def get(self, job_id: str) -> dict | None: ...
    def set(self, job_id: str, data: dict) -> None: ...

    last_summary: BatchSummary | None
